# Generated by Django 5.0.3 on 2024-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_quiz_pointsperquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='pointsperquestion',
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='level',
            field=models.CharField(default='easy', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='totalpoints',
            field=models.IntegerField(default=0),
        ),
    ]
