# Generated by Django 5.0.3 on 2024-04-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_remove_quiz_pointsperquestion_mcqquestion_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.CharField(default='understanding', max_length=100),
        ),
    ]
