# Generated by Django 5.0.3 on 2024-04-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='totalquestions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='correctlyanswered',
            field=models.IntegerField(default=0),
        ),
    ]
