# Generated by Django 5.0.2 on 2024-03-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
