# Generated by Django 5.0.2 on 2024-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
