# Generated by Django 5.0.2 on 2024-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_student_department_student_roll_no_student_semester'),
        ('courses', '0002_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
