# Generated by Django 5.0.2 on 2024-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_student_courses'),
        ('courses', '0002_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
