# Generated by Django 5.0.2 on 2024-03-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_student_courses'),
        ('courses', '0003_remove_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
